export interface Tool {
  id: string
  name: string
  description: string
  category: string
  icon: string
  popular?: boolean
  pro?: boolean
  comingSoon?: boolean
  href: string
  color: string
}

export interface Category {
  id: string
  name: string
  description: string
  icon: string
  toolCount: number
}

export const categories: Category[] = [
  { id: "pdf", name: "PDF Tools", description: "Compress, merge, split, and edit PDFs", icon: "FileText", toolCount: 20 },
  { id: "image", name: "Image Tools", description: "Resize, compress, convert, and enhance images", icon: "Image", toolCount: 15 },
  { id: "video", name: "Video Tools", description: "Trim, compress, convert, and edit videos", icon: "Video", toolCount: 13 },
  { id: "audio", name: "Audio Tools", description: "Convert, compress, and edit audio files", icon: "Music", toolCount: 13 },
  { id: "ai", name: "AI Tools", description: "Smart AI-powered content generation", icon: "Sparkles", toolCount: 15 },
  { id: "text", name: "Text Tools", description: "Format, transform, and analyze text", icon: "Type", toolCount: 23 },
  { id: "dev", name: "Developer Tools", description: "Code formatters, validators, and generators", icon: "Code", toolCount: 13 },
  { id: "seo", name: "SEO Tools", description: "Optimize your website for search engines", icon: "Search", toolCount: 12 },
  { id: "marketing", name: "Marketing Tools", description: "Create and manage marketing content", icon: "Megaphone", toolCount: 11 },
  { id: "business", name: "Business Tools", description: "Invoices, contracts, and business docs", icon: "Briefcase", toolCount: 11 },
]

export const tools: Tool[] = [
  { id: "pdf-compress", name: "Compress PDF", description: "Reduce PDF file size without losing quality", category: "pdf", icon: "FileDown", popular: true, href: "/tools/pdf-compress", color: "#EF4444" },
  { id: "pdf-merge", name: "Merge PDF", description: "Combine multiple PDFs into one document", category: "pdf", icon: "FilePlus", href: "/tools/pdf-merge", color: "#EF4444" },
  { id: "pdf-split", name: "Split PDF", description: "Split PDF into separate pages", category: "pdf", icon: "FileMinus", href: "/tools/pdf-split", color: "#EF4444" },
  { id: "pdf-to-word", name: "PDF to Word", description: "Convert PDF to editable Word documents", category: "pdf", icon: "FileType", href: "/tools/pdf-to-word", color: "#EF4444" },
  { id: "pdf-to-jpg", name: "PDF to JPG", description: "Convert PDF pages to high-quality images", category: "pdf", icon: "FileImage", href: "/tools/pdf-to-jpg", color: "#EF4444" },
  { id: "pdf-unlock", name: "Unlock PDF", description: "Remove password protection from PDF files", category: "pdf", icon: "Unlock", href: "/tools/pdf-unlock", color: "#EF4444" },
  { id: "pdf-watermark", name: "Watermark PDF", description: "Add text or image watermarks to PDF pages", category: "pdf", icon: "Droplets", href: "/tools/pdf-watermark", color: "#EF4444" },
  { id: "pdf-ocr", name: "PDF OCR", description: "Extract text from scanned PDF documents", category: "pdf", icon: "ScanLine", pro: true, href: "/tools/pdf-ocr", color: "#EF4444" },
  { id: "pdf-extract-pages", name: "Extract PDF Pages", description: "Extract specific pages from a PDF file", category: "pdf", icon: "FileOutput", href: "/tools/pdf-extract-pages", color: "#EF4444" },
  { id: "pdf-organize", name: "Organize PDF", description: "Reorder and arrange PDF pages easily", category: "pdf", icon: "AlignJustify", href: "/tools/pdf-organize", color: "#EF4444" },
  { id: "pdf-to-text", name: "PDF to Text", description: "Convert PDF documents to plain text", category: "pdf", icon: "FileType", href: "/tools/pdf-to-text", color: "#EF4444" },
  { id: "html-to-pdf", name: "HTML to PDF", description: "Convert HTML pages to PDF documents", category: "pdf", icon: "Globe", href: "/tools/html-to-pdf", color: "#EF4444" },
  { id: "jpg-to-pdf", name: "JPG to PDF", description: "Convert JPG images to PDF documents", category: "pdf", icon: "ImagePlus", href: "/tools/jpg-to-pdf", color: "#EF4444" },
  { id: "png-to-pdf", name: "PNG to PDF", description: "Convert PNG images to PDF documents", category: "pdf", icon: "ImagePlus", href: "/tools/png-to-pdf", color: "#EF4444" },
  { id: "pdf-sign", name: "Sign PDF", description: "Add digital signatures to PDF documents", category: "pdf", icon: "PenTool", pro: true, href: "/tools/pdf-sign", color: "#EF4444" },
  { id: "pdf-repair", name: "Repair PDF", description: "Fix corrupted or damaged PDF files", category: "pdf", icon: "Wrench", href: "/tools/pdf-repair", color: "#EF4444" },
  { id: "pdf-compare", name: "Compare PDF", description: "Compare two PDF files side by side", category: "pdf", icon: "GitCompare", href: "/tools/pdf-compare", color: "#EF4444" },
  { id: "pdf-redact", name: "Redact PDF", description: "Black out sensitive information in PDFs", category: "pdf", icon: "EyeOff", pro: true, href: "/tools/pdf-redact", color: "#EF4444" },
  { id: "pdf-crop", name: "Crop PDF", description: "Crop and resize PDF page margins", category: "pdf", icon: "Crop", href: "/tools/pdf-crop", color: "#EF4444" },
  { id: "pdf-metadata", name: "PDF Metadata Editor", description: "Edit PDF title, author, and properties", category: "pdf", icon: "Info", href: "/tools/pdf-metadata", color: "#EF4444" },
  { id: "image-resize", name: "Resize Image", description: "Resize images to exact dimensions", category: "image", icon: "Maximize", popular: true, href: "/tools/image-resize", color: "#8B5CF6" },
  { id: "image-compress", name: "Compress Image", description: "Optimize images for web performance", category: "image", icon: "ImageDown", href: "/tools/image-compress", color: "#8B5CF6" },
  { id: "image-convert", name: "Convert Image", description: "Convert between image formats", category: "image", icon: "RefreshCw", href: "/tools/image-convert", color: "#8B5CF6" },
  { id: "image-enhance", name: "Enhance Image", description: "AI-powered image enhancement", category: "image", icon: "Wand", pro: true, href: "/tools/image-enhance", color: "#8B5CF6" },
  { id: "remove-bg", name: "Remove Background", description: "AI background removal in one click", category: "image", icon: "Scan", popular: true, pro: true, href: "/tools/remove-bg", color: "#8B5CF6" },
  { id: "image-crop", name: "Crop Image", description: "Crop images to any aspect ratio", category: "image", icon: "Crop", href: "/tools/image-crop", color: "#8B5CF6" },
  { id: "image-upscale", name: "Upscale Image", description: "Increase image resolution with AI", category: "image", icon: "ZoomIn", pro: true, href: "/tools/image-upscale", color: "#8B5CF6" },
  { id: "remove-objects", name: "Remove Objects", description: "Remove unwanted objects from photos", category: "image", icon: "Eraser", pro: true, href: "/tools/remove-objects", color: "#8B5CF6" },
  { id: "image-to-pdf", name: "Image to PDF", description: "Convert images to PDF documents", category: "image", icon: "FileImage", href: "/tools/image-to-pdf", color: "#8B5CF6" },
  { id: "image-watermark", name: "Watermark Image", description: "Add text or image watermarks to photos", category: "image", icon: "Droplets", href: "/tools/image-watermark", color: "#8B5CF6" },
  { id: "image-blur", name: "Blur Image", description: "Apply blur effects to photos", category: "image", icon: "Aperture", href: "/tools/image-blur", color: "#8B5CF6" },
  { id: "image-rotate", name: "Rotate & Flip Image", description: "Rotate and flip images in any direction", category: "image", icon: "RotateCw", href: "/tools/image-rotate", color: "#8B5CF6" },
  { id: "ai-image-gen", name: "AI Image Generator", description: "Generate images from text prompts", category: "image", icon: "Sparkles", popular: true, pro: true, href: "/tools/ai-image-gen", color: "#8B5CF6" },
  { id: "colorize-photo", name: "Colorize Photo", description: "Add color to black and white photos", category: "image", icon: "Palette", pro: true, href: "/tools/colorize-photo", color: "#8B5CF6" },
  { id: "restore-photo", name: "Restore Old Photos", description: "Restore and enhance old damaged photos", category: "image", icon: "Heart", pro: true, href: "/tools/restore-photo", color: "#8B5CF6" },
  { id: "video-trim", name: "Trim Video", description: "Cut and trim video clips", category: "video", icon: "Scissors", href: "/tools/video-trim", color: "#06B6D4" },
  { id: "video-compress", name: "Compress Video", description: "Reduce video file size", category: "video", icon: "VideoOff", href: "/tools/video-compress", color: "#06B6D4" },
  { id: "video-convert", name: "Convert Video", description: "Convert between video formats", category: "video", icon: "Repeat", href: "/tools/video-convert", color: "#06B6D4" },
  { id: "video-to-gif", name: "Video to GIF", description: "Convert video clips to animated GIFs", category: "video", icon: "Image", href: "/tools/video-to-gif", color: "#06B6D4" },
  { id: "extract-audio", name: "Extract Audio", description: "Extract audio tracks from video files", category: "video", icon: "Music", href: "/tools/extract-audio", color: "#06B6D4" },
  { id: "merge-video", name: "Merge Video", description: "Combine multiple video clips into one", category: "video", icon: "Film", href: "/tools/merge-video", color: "#06B6D4" },
  { id: "resize-video", name: "Resize Video", description: "Resize videos to any dimensions", category: "video", icon: "Maximize", href: "/tools/resize-video", color: "#06B6D4" },
  { id: "crop-video", name: "Crop Video", description: "Crop video to focus on key areas", category: "video", icon: "Crop", href: "/tools/crop-video", color: "#06B6D4" },
  { id: "add-audio-to-video", name: "Add Audio to Video", description: "Add music or voiceover to videos", category: "video", icon: "Volume2", href: "/tools/add-audio-to-video", color: "#06B6D4" },
  { id: "change-video-speed", name: "Change Video Speed", description: "Speed up or slow down video playback", category: "video", icon: "Gauge", href: "/tools/change-video-speed", color: "#06B6D4" },
  { id: "mute-video", name: "Mute Video", description: "Remove audio from video files", category: "video", icon: "VolumeX", href: "/tools/mute-video", color: "#06B6D4" },
  { id: "rotate-flip-video", name: "Rotate & Flip Video", description: "Rotate and flip videos in any direction", category: "video", icon: "RotateCw", href: "/tools/rotate-flip-video", color: "#06B6D4" },
  { id: "video-watermark", name: "Video Watermark", description: "Add text or image watermarks to videos", category: "video", icon: "Droplets", href: "/tools/video-watermark", color: "#06B6D4" },
  { id: "audio-convert", name: "Convert Audio", description: "Convert between audio formats", category: "audio", icon: "Music", href: "/tools/audio-convert", color: "#F59E0B" },
  { id: "audio-compress", name: "Compress Audio", description: "Reduce audio file size", category: "audio", icon: "VolumeX", href: "/tools/audio-compress", color: "#F59E0B" },
  { id: "extract-audio-from-video", name: "Extract Audio from Video", description: "Extract audio tracks from video files", category: "audio", icon: "Film", href: "/tools/extract-audio-from-video", color: "#F59E0B" },
  { id: "trim-audio", name: "Trim Audio", description: "Cut and trim audio clips precisely", category: "audio", icon: "Scissors", href: "/tools/trim-audio", color: "#F59E0B" },
  { id: "merge-audio", name: "Merge Audio", description: "Combine multiple audio files into one", category: "audio", icon: "GitMerge", href: "/tools/merge-audio", color: "#F59E0B" },
  { id: "remove-noise", name: "Remove Audio Noise", description: "Remove background noise from audio", category: "audio", icon: "ShieldOff", pro: true, href: "/tools/remove-noise", color: "#F59E0B" },
  { id: "change-audio-speed", name: "Change Audio Speed", description: "Speed up or slow down audio playback", category: "audio", icon: "Gauge", href: "/tools/change-audio-speed", color: "#F59E0B" },
  { id: "audio-volume", name: "Audio Volume Booster", description: "Increase or decrease audio volume", category: "audio", icon: "Volume2", href: "/tools/audio-volume", color: "#F59E0B" },
  { id: "audio-recorder", name: "Audio Recorder", description: "Record audio directly from your browser", category: "audio", icon: "Mic", href: "/tools/audio-recorder", color: "#F59E0B" },
  { id: "audio-cutter", name: "Audio Cutter & Splitter", description: "Split audio into multiple segments", category: "audio", icon: "Scissors", href: "/tools/audio-cutter", color: "#F59E0B" },
  { id: "voice-changer", name: "Voice Changer", description: "Transform voices with AI effects", category: "audio", icon: "Headphones", pro: true, href: "/tools/voice-changer", color: "#F59E0B" },
  { id: "audio-metadata", name: "Audio Metadata Editor", description: "Edit audio tags and properties", category: "audio", icon: "Info", href: "/tools/audio-metadata", color: "#F59E0B" },
  { id: "audio-tracks", name: "Separate Audio Tracks", description: "Extract multi-language audio from video files", category: "audio", icon: "Layers", popular: true, href: "/tools/audio-tracks", color: "#F59E0B" },
  { id: "ai-writer", name: "AI Writer", description: "Generate content with AI", category: "ai", icon: "Pen", popular: true, href: "/tools/ai-writer", color: "#6366F1" },
  { id: "ai-summarize", name: "AI Summarizer", description: "Summarize any text or document", category: "ai", icon: "FileText", href: "/tools/ai-summarize", color: "#6366F1" },
  { id: "ai-rewrite", name: "AI Rewriter", description: "Rewrite content in any style", category: "ai", icon: "RefreshCw", pro: true, href: "/tools/ai-rewrite", color: "#6366F1" },
  { id: "ai-ocr", name: "AI OCR", description: "Extract text from images and PDFs", category: "ai", icon: "Scan", popular: true, pro: true, href: "/tools/ai-ocr", color: "#6366F1" },
  { id: "ai-resume", name: "AI Resume Builder", description: "Build professional resumes with AI", category: "ai", icon: "FileUser", pro: true, href: "/tools/ai-resume", color: "#6366F1" },
  { id: "ai-chat", name: "AI Chat Assistant", description: "Chat with AI for instant answers", category: "ai", icon: "MessageSquare", popular: true, href: "/tools/ai-chat", color: "#6366F1" },
  { id: "ai-image-gen", name: "AI Image Generator", description: "Generate images from text prompts", category: "ai", icon: "Image", popular: true, pro: true, href: "/tools/ai-image-gen", color: "#6366F1" },
  { id: "ai-translate", name: "AI Translator", description: "Translate text into 100+ languages", category: "ai", icon: "Languages", href: "/tools/ai-translate", color: "#6366F1" },
  { id: "ai-grammar", name: "AI Grammar Checker", description: "Fix grammar and spelling errors", category: "ai", icon: "CheckCircle", href: "/tools/ai-grammar", color: "#6366F1" },
  { id: "ai-email", name: "AI Email Writer", description: "Generate professional emails instantly", category: "ai", icon: "Mail", pro: true, href: "/tools/ai-email", color: "#6366F1" },
  { id: "ai-cover-letter", name: "AI Cover Letter Generator", description: "Create tailored cover letters", category: "ai", icon: "FileText", pro: true, href: "/tools/ai-cover-letter", color: "#6366F1" },
  { id: "ai-blog", name: "AI Blog Generator", description: "Generate blog posts with AI", category: "ai", icon: "PenTool", pro: true, href: "/tools/ai-blog", color: "#6366F1" },
  { id: "ai-social", name: "AI Social Media Generator", description: "Create social media content", category: "ai", icon: "Share2", pro: true, href: "/tools/ai-social", color: "#6366F1" },
  { id: "ai-paraphrase", name: "AI Paraphrasing Tool", description: "Rewrite text in different styles", category: "ai", icon: "Repeat", href: "/tools/ai-paraphrase", color: "#6366F1" },
  { id: "ai-code", name: "AI Code Generator", description: "Generate code from descriptions", category: "ai", icon: "Code", popular: true, pro: true, href: "/tools/ai-code", color: "#6366F1" },
  { id: "word-counter", name: "Word Counter", description: "Count words, characters, and pages", category: "text", icon: "Hash", href: "/tools/word-counter", color: "#10B981" },
  { id: "text-diff", name: "Text Diff", description: "Compare two texts side by side", category: "text", icon: "GitCompare", href: "/tools/text-diff", color: "#10B981" },
  { id: "json-formatter", name: "JSON Formatter", description: "Format and validate JSON data", category: "dev", icon: "Braces", popular: true, href: "/tools/json-formatter", color: "#22D3EE" },
  { id: "html-formatter", name: "HTML Formatter", description: "Format and beautify HTML code", category: "dev", icon: "Code", href: "/tools/html-formatter", color: "#22D3EE" },
  { id: "css-minifier", name: "CSS Minifier", description: "Minify CSS for production", category: "dev", icon: "FileCode", href: "/tools/css-minifier", color: "#22D3EE" },
  { id: "dev-js-formatter", name: "JavaScript Formatter", description: "Format and beautify JavaScript code", category: "dev", icon: "FileCode", href: "/tools/dev-js-formatter", color: "#22D3EE" },
  { id: "dev-js-minifier", name: "JavaScript Minifier", description: "Minify JavaScript for production", category: "dev", icon: "Minimize2", href: "/tools/dev-js-minifier", color: "#22D3EE" },
  { id: "dev-jwt-decoder", name: "JWT Decoder", description: "Decode and inspect JWT tokens", category: "dev", icon: "Key", href: "/tools/dev-jwt-decoder", color: "#22D3EE" },
  { id: "dev-regex-tester", name: "Regex Tester", description: "Test regular expressions in real time", category: "dev", icon: "Regex", popular: true, href: "/tools/dev-regex-tester", color: "#22D3EE" },
  { id: "dev-hash-generator", name: "Hash Generator", description: "Generate MD5, SHA1, SHA256 hashes", category: "dev", icon: "Fingerprint", href: "/tools/dev-hash-generator", color: "#22D3EE" },
  { id: "dev-base64", name: "Base64 Encoder & Decoder", description: "Encode or decode Base64 strings", category: "dev", icon: "Lock", href: "/tools/dev-base64", color: "#22D3EE" },
  { id: "dev-url-encoder", name: "URL Encoder & Decoder", description: "Encode or decode URL strings", category: "dev", icon: "Link", href: "/tools/dev-url-encoder", color: "#22D3EE" },
  { id: "dev-sql-formatter", name: "SQL Formatter", description: "Format and beautify SQL queries", category: "dev", icon: "Database", href: "/tools/dev-sql-formatter", color: "#22D3EE" },
  { id: "dev-json-minifier", name: "JSON Minifier", description: "Minify JSON data to compact form", category: "dev", icon: "Minimize2", href: "/tools/dev-json-minifier", color: "#22D3EE" },
  { id: "dev-css-formatter", name: "CSS Formatter", description: "Format and beautify CSS code", category: "dev", icon: "Paintbrush", href: "/tools/dev-css-formatter", color: "#22D3EE" },
  { id: "seo-analyzer", name: "SEO Analyzer", description: "Analyze your page for SEO issues", category: "seo", icon: "Search", popular: true, href: "/tools/seo-analyzer", color: "#F59E0B" },
  { id: "keyword-research", name: "Keyword Research", description: "Find profitable keywords", category: "seo", icon: "Key", pro: true, href: "/tools/keyword-research", color: "#F59E0B" },
  { id: "meta-tag-generator", name: "Meta Tag Generator", description: "Generate meta tags for SEO", category: "seo", icon: "Tag", href: "/tools/meta-tag-generator", color: "#F59E0B" },
  { id: "serp-preview", name: "SERP Preview Tool", description: "Preview how your page appears in Google", category: "seo", icon: "Eye", href: "/tools/serp-preview", color: "#F59E0B" },
  { id: "sitemap-generator", name: "XML Sitemap Generator", description: "Generate XML sitemaps for your website", category: "seo", icon: "Map", pro: true, href: "/tools/sitemap-generator", color: "#F59E0B" },
  { id: "robots-txt-generator", name: "Robots.txt Generator", description: "Create robots.txt files for search engines", category: "seo", icon: "Bot", href: "/tools/robots-txt-generator", color: "#F59E0B" },
  { id: "keyword-density", name: "Keyword Density Checker", description: "Check keyword density in content", category: "seo", icon: "Percent", href: "/tools/keyword-density", color: "#F59E0B" },
  { id: "seo-title-generator", name: "SEO Title Generator", description: "Generate optimized page titles", category: "seo", icon: "Type", href: "/tools/seo-title-generator", color: "#F59E0B" },
  { id: "seo-meta-desc", name: "SEO Meta Description Generator", description: "Generate compelling meta descriptions", category: "seo", icon: "AlignLeft", href: "/tools/seo-meta-desc", color: "#F59E0B" },
  { id: "redirect-checker", name: "Redirect Checker", description: "Check HTTP redirects and status codes", category: "seo", icon: "ArrowRight", href: "/tools/redirect-checker", color: "#F59E0B" },
  { id: "google-index-checker", name: "Google Index Checker", description: "Check if pages are indexed by Google", category: "seo", icon: "Globe", href: "/tools/google-index-checker", color: "#F59E0B" },
  { id: "backlink-checker", name: "Backlink Checker", description: "Check backlinks to any website", category: "seo", icon: "ExternalLink", pro: true, href: "/tools/backlink-checker", color: "#F59E0B" },
  { id: "invoice-generator", name: "Invoice Generator", description: "Create professional invoices", category: "business", icon: "FileSpreadsheet", href: "/tools/invoice-generator", color: "#10B981" },
  { id: "receipt-generator", name: "Receipt Generator", description: "Generate receipts for transactions", category: "business", icon: "Receipt", href: "/tools/receipt-generator", color: "#10B981" },
  { id: "quotation-generator", name: "Quotation Generator", description: "Create professional quotations", category: "business", icon: "FileText", href: "/tools/quotation-generator", color: "#10B981" },
  { id: "purchase-order-generator", name: "Purchase Order Generator", description: "Generate purchase orders easily", category: "business", icon: "ShoppingCart", href: "/tools/purchase-order-generator", color: "#10B981" },
  { id: "business-proposal", name: "Business Proposal Generator", description: "Create winning business proposals", category: "business", icon: "Briefcase", pro: true, href: "/tools/business-proposal", color: "#10B981" },
  { id: "contract-generator", name: "Contract Generator", description: "Generate professional contracts", category: "business", icon: "FileSignature", pro: true, href: "/tools/contract-generator", color: "#10B981" },
  { id: "profit-margin", name: "Profit Margin Calculator", description: "Calculate profit margins instantly", category: "business", icon: "TrendingUp", href: "/tools/profit-margin", color: "#10B981" },
  { id: "gst-vat-calculator", name: "GST/VAT Calculator", description: "Calculate GST and VAT instantly", category: "business", icon: "Calculator", href: "/tools/gst-vat-calculator", color: "#10B981" },
  { id: "salary-calculator", name: "Salary Calculator", description: "Calculate gross and net salary", category: "business", icon: "Wallet", href: "/tools/salary-calculator", color: "#10B981" },
  { id: "business-name-generator", name: "Business Name Generator", description: "Generate creative business names", category: "business", icon: "Lightbulb", href: "/tools/business-name-generator", color: "#10B981" },
  { id: "qr-code-generator", name: "QR Code Generator", description: "Generate QR codes for any URL", category: "business", icon: "QrCode", href: "/tools/qr-code-generator", color: "#10B981" },
  { id: "qr-generator", name: "QR Code Generator", description: "Generate QR codes for any URL", category: "marketing", icon: "QrCode", href: "/tools/qr-generator", color: "#EC4899" },
  { id: "utm-builder", name: "UTM Builder", description: "Create UTM tracking parameters", category: "marketing", icon: "Link", href: "/tools/utm-builder", color: "#EC4899" },
  { id: "hashtag-generator", name: "Hashtag Generator", description: "Generate trending hashtags for posts", category: "marketing", icon: "Hash", href: "/tools/hashtag-generator", color: "#EC4899" },
  { id: "social-caption", name: "Social Media Caption Generator", description: "Generate engaging social captions", category: "marketing", icon: "MessageCircle", popular: true, href: "/tools/social-caption", color: "#EC4899" },
  { id: "email-subject", name: "Email Subject Line Generator", description: "Generate catchy email subject lines", category: "marketing", icon: "Mail", href: "/tools/email-subject", color: "#EC4899" },
  { id: "cta-generator", name: "Call-To-Action Generator", description: "Generate compelling CTAs", category: "marketing", icon: "MousePointer", href: "/tools/cta-generator", color: "#EC4899" },
  { id: "landing-page-headline", name: "Landing Page Headline Generator", description: "Generate high-converting headlines", category: "marketing", icon: "Heading", pro: true, href: "/tools/landing-page-headline", color: "#EC4899" },
  { id: "ad-copy", name: "Ad Copy Generator", description: "Generate effective ad copy", category: "marketing", icon: "Megaphone", pro: true, href: "/tools/ad-copy", color: "#EC4899" },
  { id: "marketing-calendar", name: "Marketing Calendar Generator", description: "Plan your marketing calendar", category: "marketing", icon: "Calendar", href: "/tools/marketing-calendar", color: "#EC4899" },
  { id: "youtube-title", name: "YouTube Title Generator", description: "Generate SEO-optimized video titles", category: "marketing", icon: "Youtube", popular: true, href: "/tools/youtube-title", color: "#EC4899" },
  { id: "youtube-desc", name: "YouTube Description Generator", description: "Generate YouTube video descriptions", category: "marketing", icon: "FileText", href: "/tools/youtube-desc", color: "#EC4899" },
  { id: "unit-converter", name: "Unit Converter", description: "Convert between any units", category: "text", icon: "ArrowLeftRight", href: "/tools/unit-converter", color: "#10B981" },
  { id: "case-converter", name: "Case Converter", description: "Convert text between cases instantly", category: "text", icon: "CaseSensitive", href: "/tools/case-converter", color: "#10B981" },
  { id: "text-json-formatter", name: "JSON Formatter", description: "Format, validate, and minify JSON", category: "text", icon: "Braces", popular: true, href: "/tools/text-json-formatter", color: "#10B981" },
  { id: "text-cleaner", name: "Text Cleaner", description: "Remove extra spaces, lines, and formatting", category: "text", icon: "Brush", href: "/tools/text-cleaner", color: "#10B981" },
  { id: "find-replace", name: "Find & Replace", description: "Find and replace text in bulk", category: "text", icon: "Replace", href: "/tools/find-replace", color: "#10B981" },
  { id: "lorem-ipsum", name: "Lorem Ipsum Generator", description: "Generate placeholder text for design", category: "text", icon: "AlignLeft", href: "/tools/lorem-ipsum", color: "#10B981" },
  { id: "text-to-slug", name: "Text to Slug", description: "Convert text to URL-friendly slugs", category: "text", icon: "Link", href: "/tools/text-to-slug", color: "#10B981" },
  { id: "base64", name: "Base64 Encoder & Decoder", description: "Encode or decode Base64 strings", category: "text", icon: "Lock", href: "/tools/base64", color: "#10B981" },
  { id: "duplicate-remover", name: "Duplicate Line Remover", description: "Remove duplicate lines from text", category: "text", icon: "Trash2", href: "/tools/duplicate-remover", color: "#10B981" },
  { id: "text-sorter", name: "Text Sorter", description: "Sort lines alphabetically or numerically", category: "text", icon: "ArrowUpDown", href: "/tools/text-sorter", color: "#10B981" },
  { id: "char-counter", name: "Character Counter", description: "Count characters, words, and sentences", category: "text", icon: "Hash", href: "/tools/char-counter", color: "#10B981" },
  { id: "text-js-formatter", name: "JavaScript Formatter", description: "Format and beautify JavaScript code", category: "text", icon: "FileCode", href: "/tools/text-js-formatter", color: "#10B981" },
  { id: "text-js-minifier", name: "JavaScript Minifier", description: "Minify JavaScript for production", category: "text", icon: "Minimize2", href: "/tools/text-js-minifier", color: "#10B981" },
  { id: "jwt-decoder", name: "JWT Decoder", description: "Decode and inspect JWT tokens", category: "text", icon: "Key", href: "/tools/jwt-decoder", color: "#10B981" },
  { id: "regex-tester", name: "Regex Tester", description: "Test regular expressions in real time", category: "text", icon: "Regex", popular: true, href: "/tools/regex-tester", color: "#10B981" },
  { id: "hash-generator", name: "Hash Generator", description: "Generate MD5, SHA1, SHA256 hashes", category: "text", icon: "Fingerprint", href: "/tools/hash-generator", color: "#10B981" },
  { id: "text-base64", name: "Base64 Encoder & Decoder", description: "Encode or decode Base64 strings", category: "text", icon: "Lock", href: "/tools/text-base64", color: "#10B981" },
  { id: "url-encoder", name: "URL Encoder & Decoder", description: "Encode or decode URL strings", category: "text", icon: "Link", href: "/tools/url-encoder", color: "#10B981" },
  { id: "sql-formatter", name: "SQL Formatter", description: "Format and beautify SQL queries", category: "text", icon: "Database", href: "/tools/sql-formatter", color: "#10B981" },
  { id: "text-json-minifier", name: "JSON Minifier", description: "Minify JSON data to compact form", category: "text", icon: "Minimize2", href: "/tools/text-json-minifier", color: "#10B981" },
  { id: "text-css-formatter", name: "CSS Formatter", description: "Format and beautify CSS code", category: "text", icon: "Paintbrush", href: "/tools/text-css-formatter", color: "#10B981" },
]

export const testimonials = [
  {
    name: "Alex Chen",
    role: "Product Designer",
    company: "TechCorp",
    content: "PhoenixTools AI has completely transformed my workflow. The AI tools alone save me hours every day.",
    avatar: "AC",
    rating: 5,
  },
  {
    name: "Sarah Johnson",
    role: "Marketing Director",
    company: "GrowthLab",
    content: "Finally, a utility platform that doesn't look like it's from 2010. The design and UX are absolutely breathtaking.",
    avatar: "SJ",
    rating: 5,
  },
  {
    name: "Marcus Williams",
    role: "Full-Stack Developer",
    company: "DevStudio",
    content: "The developer tools are incredibly polished. JSON formatter, code minifier — everything just works perfectly.",
    avatar: "MW",
    rating: 5,
  },
  {
    name: "Emily Rodriguez",
    role: "Small Business Owner",
    company: "EcoStore",
    content: "I use the PDF tools daily. The quality and speed are unmatched. Worth every penny for the Pro plan.",
    avatar: "ER",
    rating: 5,
  },
]

export const stats = [
  { label: "Active Users", value: "50K+" },
  { label: "Files Processed", value: "10M+" },
  { label: "Tools Available", value: "500+" },
  { label: "Countries", value: "180+" },
]

export const faqs = [
  {
    q: "What is PhoenixTools AI?",
    a: "PhoenixTools AI is a premium, all-in-one utility platform that combines PDF tools, image editors, video converters, AI features, and more into a single beautiful ecosystem. Think of it as the Apple of utility websites.",
  },
  {
    q: "Is there a free plan?",
    a: "Yes! We offer a generous free plan with limited daily usage and standard processing speed. Upgrade to Pro for unlimited access, priority processing, and advanced features.",
  },
  {
    q: "Are my files secure?",
    a: "Absolutely. All files are processed with enterprise-grade encryption. Files are automatically deleted from our servers after processing. We never share or store your data.",
  },
  {
    q: "What makes PhoenixTools different?",
    a: "We combine the functionality of Canva, iLovePDF, 123Apps, and modern AI products into one seamless platform with a premium, minimalist design. Every tool feels like a dedicated SaaS product.",
  },
  {
    q: "Can I use it for my business?",
    a: "Absolutely. Our Pro and Enterprise plans are designed for businesses of all sizes. We offer team accounts, API access, and dedicated support.",
  },
]
